apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-a2mm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0031-tenant/ci10t-776-0031-app/devfile-sample-a2mm@sha256:9bb368c980bd21c6eafc441465043453146c7f9a5a62987ce0abfe8cff1839ef
        name: my-nodejs
        resources: {}
status: {}
